# MÉTODOS ESTADÍSTICOS PARA LA INVESTIGACIÓN CIENTÍFICA

El curso Métodos Estadísticos para la Investigación Científica es de naturaleza teórico-práctico y pertenece a la línea curricular ciencia de los alimentos. El objetivo de este curso es proporcionar a los maestrantes las herramientas estadísticas necesarias para procesar, analizar e interpretar datos en el contexto descriptivo e inferencial, basado en pruebas estadísticas para una muestra, dos muestras independientes, dos muestras relacionadas, tres o más muestras independientes y tres o más muestras relacionadas con un enfoque univariado, bivariado y multivariado. Los maestrantes aprenderán a seleccionar y aplicar los métodos adecuados para abordar preguntas de investigación en el campo de los alimentos, y a comunicar los resultados de manera clara y rigurosa. Los contenidos están distribuidos en tres unidades didácticas; I unidad didáctica: Fundamentos y herramientas estadísticas aplicadas a la investigación científica. II unidad didáctica: Análisis univariado y multivariado de datos cuantitativos. III unidad didáctica: Métodos estadísticos para el análisis de datos cualitativos y categóricos.